import Cross.CrossModelMock;
import Cross.CrossPanelPresenter;
import Cross.CrossPanelView;
import sun.applet.Main;

import javax.swing.*;
import java.awt.*;

/**
 * Created by Su on 22/03/17.
 */
public class LegGui extends JFrame {
    private JPanel MainPanel;
    private JTextArea console;
    private JPanel SideViewPanel;
    private JPanel FrontViewPanel;
    private JScrollPane consoleScrollPane;
    private JPanel TopViewPanel;

    public JPanel getMainPanel() {
        return MainPanel;
    }


    public CrossPanelView getSideCrossView() {
        return (CrossPanelView) SideViewPanel;
    }

    public CrossPanelView getFrontCrossView() {
        return (CrossPanelView) FrontViewPanel;
    }

    public CrossPanelView getTopCrossView() {
        return (CrossPanelView) TopViewPanel;
    }

    private void createUIComponents() {

        SideViewPanel = new CrossPanelView();
        FrontViewPanel = new CrossPanelView();
        TopViewPanel = new CrossPanelView();

        console = new JTextArea();
        console.setEditable(false);
        console.setLineWrap(true);
    }

    public void appendLogMessage(String message) {
        console.append(message);
        console.setCaretPosition(console.getDocument().getLength());
    }

    public JFrame createFrame() {

        JFrame frame = new JFrame();
        frame.setTitle("U.R.S.A. VooDoo leg controller");
        frame.setContentPane(MainPanel);
        frame.setMinimumSize(new Dimension(300, 300));
        frame.setSize(MainPanel.getPreferredSize());
        return frame;
    }


    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        MainPanel = new JPanel();
        MainPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(3, 2, new Insets(0, 0, 0, 0), -1, -1));
        MainPanel.setBackground(new Color(-15132391));
        MainPanel.setForeground(new Color(-133635));
        SideViewPanel.setBackground(new Color(-6261268));
        SideViewPanel.setEnabled(true);
        MainPanel.add(SideViewPanel, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, new Dimension(-1, 100), new Dimension(400, 400), null, 0, false));
        FrontViewPanel.setBackground(new Color(-1302483));
        MainPanel.add(FrontViewPanel, new com.intellij.uiDesigner.core.GridConstraints(0, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, new Dimension(-1, 100), new Dimension(400, 400), null, 0, true));
        consoleScrollPane = new JScrollPane();
        MainPanel.add(consoleScrollPane, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 2, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        console.setBackground(new Color(-9474193));
        console.setForeground(new Color(-1));
        console.setInheritsPopupMenu(true);
        consoleScrollPane.setViewportView(console);
        TopViewPanel.setBackground(new Color(-11049236));
        MainPanel.add(TopViewPanel, new com.intellij.uiDesigner.core.GridConstraints(1, 1, 2, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, new Dimension(-1, 100), new Dimension(400, 400), null, 0, true));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return MainPanel;
    }
}
